plugins {
    id 'com.android.application'
}

android {
    namespace 'com.easternwood.capture.runner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.easternwood.capture.runner'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
